name: Auto-merge PRs

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    # Only run for dependabot or kuasar-mknd
    if: |
      github.event.pull_request.user.login == 'dependabot[bot]' ||
      github.event.pull_request.user.login == 'kuasar-mknd'
    steps:
      - name: Enable auto-merge
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          for i in {1..3}; do
            gh pr merge --auto --squash "$PR_URL" && break || {
              echo "Attempt $i failed, retrying in 5 seconds..."
              sleep 5
            }
          done
